// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header"; // Importeren

const inter = Inter({ subsets: ["latin"] });

// Je kunt hier later ook je globale metadata ophalen
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
      <body className={inter.className}>
        <Header /> {/* Header hier toevoegen */}
        <main>{children}</main>
        {/* Voeg hier later een Footer component toe */}
      </body>
    </html>
  );
}
